### PR TITLE
Move all docs to docs folder and clean project root

### PR DESCRIPTION
**Pull request by IgorGov**
The idea is to have the minimum files at the root folder.
Move all docs files to docs folder.
All scripts to "devop" folder.
Docker file to agent folder (as it related to agent only and not to CLI)

### CODE REVIEW

**Review by RoyUP9 — COMMENTED** [review]
root makefile: 
Lines 47 and 51
change path to devops folder

**Review by RoyUP9 — COMMENTED** [review]
build-push-featurebranch script not working

**Review by RoyUP9 — APPROVED** [review]

**Review by RoyUP9 — CHANGES_REQUESTED** [review]
fix Contributing header

**Review by mertyildiran — COMMENTED** [review]
Will the issue templates work outside the `.github/` directory?

**Review by RoyUP9 — DISMISSED** [review]

**Comment by IgorGov** [comment]
> Will the issue templates work outside the `.github/` directory?

Good catch! Github supports only one location for issue template which is .github folder
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Review by RoyUP9 — APPROVED** [review]

**Review by mertyildiran — APPROVED** [review]

**Pull request merged**
