### PR TITLE
Upgrade Basenine version to `v0.7.0`

### PR DESCRIPTION
**Pull request by mertyildiran**
Notable changes:
- The entry ID is now a string instead of an integer.
- Instead of `leftOff(-1)` we use `leftOff("latest")` in parallel to the ID data type change.

### CODE REVIEW

**Comment by mertyildiran** [comment]
I have no idea how am I going to fix the merge conflicts.

**Review by nimrod-up9 — APPROVED** [review]

**Comment by mertyildiran** [comment]
This PR is approved but I'm unable to fix the merge conflicts.

**Comment by gadotroee** [comment]
> This PR is approved but I'm unable to fix the merge conflicts.

I talked to nimrod and understood he checked the code without addressing the conflicts and just wanted to mark the code he checked somehow (because he has no comments on what he saw).

Before it can be merged, someone from the FE developers that worked on the latest changes (that created the conflicts) should help solve it. 

I think it will be on Monday because our team is not working tomorrow.

**Comment by gadotroee** [comment]
I tried to solve the conflicts from what I know (but didn't wanted to pushed some changes that adds a lot of commits (form develop) with changes of my own) it is inside this PR https://github.com/up9inc/mizu/pull/984 and maybe you can take a look and see if it make sense and maybe it can be taken to this branch or  or merged directly from the second PR.

I ran it and it is working from my first sanity check of building the image and running mizu with --set agent-image of the new image. but it was not tested more deeply with all functionality. (I'm thinking about running the acceptance tests on the branch just to get better feeling of things that are working)

@mertyildiran let me know what do think.

**Comment by mertyildiran** [comment]
Closing in favor of https://github.com/up9inc/mizu/pull/984

**Pull request closed without merging**
