### PR TITLE
Set a default value for `SEM_VER` build-time variable in `Dockerfile`

### PR DESCRIPTION
**Pull request by mertyildiran**
This PR;

Sets a default value for `SEM_VER` build-time variable in `Dockerfile`

Also fixes a runtime error that happens when the API server's version is not a valid SemVer:

```
$ ./cli/bin/mizu__ view                                                                                                                                                                                       ok  10s  17:52:37 
Establishing connection to k8s cluster...
Mizu is available at http://localhost:8899/mizu
Update available! 0.0.0 -> 0.18.0 (curl -Lo mizu https://github.com/up9inc/mizu/releases/download/0.18.0/mizu_linux_amd64 && chmod 755 mizu)
Unhandled panic: runtime error: index out of range [0] with length 0
 stack: goroutine 1 [running]:
runtime/debug.Stack(0xc00011f558, 0x21a8180, 0xc0001544b0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/up9inc/mizu/cli/cmd/goUtils.HandleExcWrapper.func1()
	/home/mertyildiran/Documents/up9/mizu/cli/cmd/goUtils/funcWrappers.go:13 +0x5b
panic(0x21a8180, 0xc0001544b0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/up9inc/mizu/shared/semver.SemVersion.Breakdown(0x0, 0x0, 0x0, 0x0, 0x0, 0xc00061b828, 0x1d8fd25, 0xc00049e2c0)
	/home/mertyildiran/Documents/up9/mizu/shared/semver/semver.go:20 +0xe5
github.com/up9inc/mizu/shared/semver.SemVersion.Major(...)
	/home/mertyildiran/Documents/up9/mizu/shared/semver/semver.go:24
github.com/up9inc/mizu/cli/mizu/version.CheckVersionCompatibility(0xc00061b958, 0x1a, 0xc000612500, 0xc000612520)
	/home/mertyildiran/Documents/up9/mizu/cli/mizu/version/versionCheck.go:27 +0x7e
github.com/up9inc/mizu/cli/cmd.runMizuView()
	/home/mertyildiran/Documents/up9/mizu/cli/cmd/viewRunner.go:63 +0x456
github.com/up9inc/mizu/cli/cmd.glob..func8(0x2fbb780, 0x306c738, 0x0, 0x0, 0x0, 0x0)
	/home/mertyildiran/Documents/up9/mizu/cli/cmd/view.go:16 +0x85
github.com/spf13/cobra.(*Command).execute(0x2fbb780, 0x306c738, 0x0, 0x0, 0x2fbb780, 0x306c738)
	/home/mertyildiran/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x2fbb000, 0x237cac8, 0xc00010f140, 0x0)
	/home/mertyildiran/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/mertyildiran/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/up9inc/mizu/cli/cmd.Execute()
	/home/mertyildiran/Documents/up9/mizu/cli/cmd/root.go:60 +0xb9
reflect.Value.call(0x1f7d9c0, 0x237ca18, 0x13, 0x22b1932, 0x4, 0x306c738, 0x0, 0x0, 0xc000193e88, 0xbd35ac, ...)
	/usr/local/go/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0x1f7d9c0, 0x237ca18, 0x13, 0x306c738, 0x0, 0x0, 0xbc1745, 0xc000078710, 0xbc662a)
	/usr/local/go/src/reflect/value.go:337 +0xb9
github.com/up9inc/mizu/cli/cmd/goUtils.HandleExcWrapper(0x1f7d9c0, 0x237ca18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/mertyildiran/Documents/up9/mizu/cli/cmd/goUtils/funcWrappers.go:25 +0x24f
main.main()
	/home/mertyildiran/Documents/up9/mizu/cli/mizu.go:9 +0x4a
```

### CODE REVIEW

**Review by gadotroee — APPROVED** [review]
From what I understand this is happening when building the docker image locally (in CI publish the parameters is always set to something).

I thought we did it in our "build push feature branch" script but maybe it is missing.
I'm approving because the change looks good but I will double check if we did pass it (maybe it is missing and it can be the change.

**Comment by gadotroee** [comment]
https://github.com/up9inc/mizu/blob/3f01f20f0c70786cec7b0af6da0a45a78b4ab120/cli/Makefile#L6 this line should add the Env var in when running and it is the value that passed when we are using make cli or make agent.. 
so I think it should be "0.0.0" passed to the docker image if not specified other wise

**Comment by mertyildiran** [comment]
> From what I understand this is happening when building the docker image locally (in CI publish the parameters is always set to something).
> 
> I thought we did it in our "build push feature branch" script but maybe it is missing. I'm approving because the change looks good but I will double check if we did pass it (maybe it is missing and it can be the change.

`devops/build-push-featurebranch.sh` cannot be used by the outsiders.

e.g. this is how I build and publish my agent images for the development:

```shell
docker build . -t mertyildiran/mizuagent:latest && docker push mertyildiran/mizuagent:latest
```

**Comment by gadotroee** [comment]
> e.g. this is how I build and publish my agent images for the development:

you are absolutely right, so this is kind of no harm (because if you set this arg (using --build-arg) it will override, so it will help developers who works without our scripts.

**Review by nimrod-up9 — APPROVED** [review]

**Review by RamiBerm — APPROVED** [review]

**Pull request merged**
