### PR TITLE
Add GraphQL detection

### PR DESCRIPTION
**Pull request by mertyildiran**
Screenshot from 2022-04-08 21-03-04
Screenshot from 2022-04-08 21-03-09
Screenshot from 2022-04-08 21-03-17
Screenshot from 2022-04-08 21-03-40

### CODE REVIEW

**Review by gadotroee — APPROVED** [review]

**Review by gadotroee — CHANGES_REQUESTED** [review]
I see one small conflict but afte rsolving it I can approve

**Review by gadotroee — APPROVED** [review]

**Comment by gadotroee** [comment]
@mertyildiran 

I see that this snyk failure is because of the new graphql library. 
From what I see in snyk (maybe you can't see it we can upgrade the version of the dependent library ("encode" if I remember correctly) and maybe then we won't have this failure). 
I can add you permission if you want to be able to see it too)

**Comment by mertyildiran** [comment]
@gadotroee yes, I tried to access the Synk dashboard but I couldn't.

**Comment by gadotroee** [comment]
You have button to request access, if you can click on it I will approve the request.

**Comment by mertyildiran** [comment]
I have tried many versions of https://pkg.go.dev/golang.org/x/crypto In every version, they have a different security vulnerability. So, I guess we can't merge it until the dependencies update.

**Comment by mertyildiran** [comment]
Turned this PR to draft because of security vulnerabilities.

**Comment by mertyildiran** [comment]
@gadotroee I have fixed the vulns by forking the subject library into here https://github.com/mertyildiran/gqlparser

**Review by gadotroee — APPROVED** [review]

**Pull request merged**
