### PR TITLE
Fixed default mime type to empty string instead of text/html

### PR DESCRIPTION
**Pull request by RoyUP9**

### CODE REVIEW

**Comment by RoyUP9** [comment]
@mertyildiran This PR fixes default mime type to be empty string, so there is a need for changing some of the entries in the tests.
Can you help me fix those entries in the test?

**Review by nimrod-up9 — APPROVED** [review]

**Comment by mertyildiran** [comment]
@RoyUP9 checking...

**Comment by mertyildiran** [comment]
@RoyUP9 done.

**Comment by RoyUP9** [comment]
> @RoyUP9 done.

Thx!

**Review by nimrod-up9 — APPROVED** [review]

**Pull request merged**
