### PR TITLE
Repurpose selected entries as a filtering mechanism

### PR DESCRIPTION
**Pull request by mertyildiran**
https://user-images.githubusercontent.com/2502080/142929951-1e5481ca-e173-426b-9729-c06a3a8c87a2.mp4

### CODE REVIEW

**Comment by gadotroee** [comment]
This is a good feature idea but not related to the fix we described in the ticket.
We can open ticket to achieve this functionally.

**Comment by mertyildiran** [comment]
Merger of https://github.com/up9inc/mizu/pull/501 will break this PR. Merge https://github.com/up9inc/mizu/pull/501 first, fix the conflicts in here.

**Comment by mertyildiran** [comment]
Realized https://github.com/up9inc/mizu/pull/501 cannot be merged now, see https://github.com/up9inc/mizu/pull/501#issuecomment-982276161

**Comment by mertyildiran** [comment]
Turning into draft again. Merge https://github.com/up9inc/mizu/pull/513 first.

**Pull request closed without merging**
